config/routes.rb
Rampup::Application.routes.draw do

  resources :applications

  root to: "welcome#index"

  get "welcome/index"
  
  match 'viewapps' => 'applications#viewapps'

end

app/models/application.rb
class Application < ActiveRecord::Base
  attr_accessible :name, :q1
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery



end

app/controllers/applications_controller.rb
class ApplicationsController < ApplicationController
  http_basic_authenticate_with name: "sib", password: "sibpass", except:  [:index, :create, :new]

    def new
    end
    
    def create
  	 @app = Application.new(params[:applications])
  	
    if @app.save
      flash[:notice] = "Your application has been submitted"
      redirect_to action: "index"
    else
      render 'new'
    end

    end

    def show
  	 @app = Application.find(params[:id])
    end

    def index
    end

    def viewapps
      @apps = Application.all
    end


  end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/applications_helper.rb
module ApplicationsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/applications/index.html.erb
<% if flash[:notice] %>
    <div id="notice"><%= flash[:notice] %></div>
<% end %>


<h1>This is where the application info goes</h1>
<h2>You have until yesterday to apply</h2>
<%= link_to "Apply Here", new_application_path %>

app/views/applications/new.html.erb
<h1>Application Page</h1>

<%= form_for :applications, url: applications_path do |f| %>
  <p>
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </p>
 
  <p>
    <%= f.label :q1, "How do you like your steak" %><br>
    <%= f.text_area :q1 %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
<% end %>

<%= link_to "back", applications_path %>

app/views/applications/show.html.erb
<p>
  <strong>Name:</strong>
  <%= @app.name %>
</p>
 
<p>
  <strong>How they like steak:</strong>
  <%= @app.q1 %>
</p>

 
<%= link_to "back", viewapps_path %>

app/views/applications/viewapps.html.erb
<h1>List Students</h1>


<table>
	<tr>
		<th>Name</th>
		<th>Steak</th>
	</tr>

	<% @apps.each do |app| %>
	<tr>
		<td><%= app.name %></td>
		<td><%= app.q1 %></td>
		<td><%= link_to 'Show', applications_path %></td>
	</tr>
	<% end %>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Rampup</title>
  <%= favicon_link_tag %>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/welcome/index.html.erb
<h1>This will be the RampUp landing page</h1>
<h2>Project based program for high school students to learn web development skills from industry professionals<h2>
<%= link_to "Application Info", controller: "applications" %>